server:
  port:8080
spring:
  application:
    name: account
  datasource:
    password: 1922
    url: jdbc:mysql://localhost:3306/account?useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show-sql: true


